name: Artifactory Webhook Handler

on:
  workflow_dispatch:
    inputs:
      payload:
        description: 'Webhook payload'
        required: false

jobs:
  handle-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Print Webhook Payload
        run: |
          echo "Webhook Payload Input:"
          echo '${{ github.event.inputs.payload }}'
          echo "Full Event Context:"
          echo '${{ toJson(github.event) }}'